### ISSUE TITLE
The bcrypt.hashpw(val1, val2) function always produces the same output even if the values are different.

### ISSUE THREAD

**Issue by Eta06** [pyca/bcrypt#691] opened 2023-12-10 21:54 UTC
In this part of the code, even though the variable typed_password changes, it still continues to match the input. Even when the firstdata and second data variables also change due to the change in typed_password, the part of the code which combines these two pieces of data still continues to produce the same hashed output no matter what. I am unable to understand why this happens.

- Python Version: [3.7.9](https://www.python.org/downloads/release/python-379/)
- bcrypt Version [4.0.1](https://pypi.org/project/bcrypt/4.0.1/)

I would be very happy if you could help :)

```
@app.route("/api/v1/login", methods=["POST", "GET"])
@limiter.limit("5 per minute")
def apilogin():
    try:
        args = request.args.get("query")
        if args is None:
            newimage = create_image()
            return {"success": False, "message": "No Arguments Given.", "captcha": newimage[0]}
        try:
            try:
                args = base64.b64decode(args).decode("utf-8")
            except:
                args = base64.b64decode(args[2:-1]).decode("utf-8")
            try:
                args = json.loads(args)
                try:
                    username = args["username"]
                    password = args["password"]
                    imagedata = args["imagedata"]
                    captcha = args["captcha"]
                    if username is None or password is None or captcha is None or imagedata is None:
                        return {"success": False, "message": "Fill all the required fields."}
                    else:
                        usernamevalid, username = validation_checker.checker(username)
                        passwordvalid, password = validation_checker.validate_password(password)
                        if not usernamevalid:
                            return {"success": False, "message": "Invalid Username!"}
                        if not passwordvalid:
                            return {"success": False, "message": "Invalid Password!"}
                        captchafilter = {
                            "Value": captcha,
                            "Image": imagedata
                        }
                        print(password)
                        captchacollection = db["captchas"]
                        captcharesult = captchacollection.find_one(captchafilter)
                        if captcharesult is None:
                            return {"success": False, "message": "Captcha is incorrect or expired!"}
                        user_filter = {"username": username}
                        user_collection = db["repuusers"]
                        user_result = user_collection.find_one(user_filter)
                        if user_result is None:
                            return {"success": False, "message": "Username or Password is incorrect!"}
                        else:
                            extralayerforpass = user_result["usrsalt"]
                            rapi = user_result["rapi"]
                            real_password = user_result["password"]
                            typed_password = password.encode("utf-8")
                            with open("master.key", "rb") as f:
                                master_key = f.read()
                            with open("master.key2", "rb") as f:
                                master_key_two = f.read()
                            firstdata = master_key + typed_password + rapi + typed_password + user_result["email"].encode("utf-8") + extralayerforpass + master_key_two + username.encode("utf-8")
                            print("First Data:", firstdata)
                            seconddata = extralayerforpass + user_result["email"].encode("utf-8") + username.encode("utf-8") + typed_password
                            print("Second Data:", seconddata)
                            hashedpass = bcrypt.hashpw(firstdata, seconddata)
                            print("Hashed Password:", hashedpass)

                            if user_result["totaltries"] > 20:
                                return {"success": False, "message": "Too many tries!"}

                            if hashedpass == real_password:
                                print("Hased Pass:", hashedpass)
                                print("Real Pass:", real_password)
                                user_collection.update_one({"username": username}, {"$set": {"totaltries": 0}})
                                client_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
                                lme.infologger({"date": datetime.datetime.utcnow(),
                                                "message": f"User logged in with IP: {client_ip}"})
                                return {"success": True, "rapi": rapi.decode("utf-8"), "message": "Login Success"}
                            else:
                                user_collection.update_one({"username": username}, {"$set": {"totaltries": user_result["totaltries"] + 1}})
                                return {"success": False, "message": "Login error"}
                except:
                    return {"success": False, "message": "API Request Must Contain All Required Parameters!"}
            except:
                return {"success": False, "message": "API Request Must Be JSON!"}
        except:
            return {"success": False, "message": "API Request Must Be Base64 Encoded!"}
    except:
        newimage = create_image()
        return {"success": False, "message": "No Arguments Given.", "captcha": newimage[0]}

```

**Comment by alex** [comment] 2023-12-10 22:54
First, please provide a _minimal_ reproducer script that we can run. We have no way to test or verify what you've posted.

Second, contrary to your description, `typed_password` is assigned to a single time in this code, so I'm not able to follow your description of what you're expecting vs. what you're seeing.

**Comment by Eta06** [comment] 2023-12-11 20:16
First of all, I apologize for the lack of information. I have now sent you an example code, which has some dummy sample data. You can test it in this way. I have given you some data stored in the database statically. If there is anything I have missed, please let me know.

```
import base64
import json
import bcrypt

from datetime import datetime


def apilogin():
    username = "TestUser"
    # Definer user password is "Password0"
    password = input("Password: ")

    # Real password saved in database and generated with bcrypt (Dummy)
    real_password = b'$2b$11$ssr3qHnRez3iKkd8TnbOpu3LWoioi9SYgvvgQZRN5uzyEBDjm4/wC'

    typed_password = password.encode("utf-8")

    # Other Values (Dummy)
    master_key = b"Z0FBQUFBQmxkMm5kdFVDLVhnY1JZY3I5UEMwckUyU0tRTW43NDRlSW1PTFMyVG1vSGFUYmlkMTRnMFE0RWtsLXhzWUxNN0NibVMxMm0tUXlQZlpTX2lock1VSjJBc3ROUVJsSE92YUVsZW9EZU52dDFNS3NqeDdvNUFBR3Z1ZmF4OU9CMDdMcTI2VU9XSjZWNWl5ZVdfcGlENWtqNVdYeGc0RE5MZUt4dmNSUDJUQWRnX01tbTBHN1RweThScXVtRy1lcVpFWmdHcnduMnpWUmVvX29PVWR1Z1JQaFUySDdJMFIwZENqMUQtT2ZBM2V4dEdoek5QX2RXenZHeDUzTzRKb18zTnh3XzVFdXJLYURoVmkwUkg3cDBUUzZ6Q1BaUS1velp6QW1QM1RCZzIxS0VxbmtiZElfR3h2STVHMk5DNWhJTVBBSnBlcTgyakRhVXRReGVMWU1PSjdXb1FHWWYtYW1tLXFtMkZxVS1XX2hPOE9KaV9kTjNrUG1fdDRHMjRjVk9UV1RlNHY4Z1dTdFhPdDk0aFkxUzIwZnhvbU13NzlhUGRENjFobURFdGYxSURQX0V0Vm9uaWh3MGE2UlRhcER6M2JBa1NPakZxdDFIVEhVbENLZTJCdDBSdlZ2ZmFZdDV5SUZQaUVFczRGZjAtMFA2Z0o2NFhlMUNHa3kzTkNDa2laSzlSNG1mblBSNUpUb3ByOW1oak1oaEdxbWpYbjFkWHgyazEyc1BKVDZOUy10QXJBS0tzNWlRV2JjcFF1RXYzXzNHbFRZallKTjctYnZDaXNLLTUxblhSTkhUU183NC1leGVGSFU1VjBYQ2xwM2tYWVNzZHRrOWxVakZtR0hZTV9RQzA5cDlvYnkzN3QtOEVsNnpPNGduaWZwc1BhMGxMbnlBeE9lTzFWX0lmTS1VLUZiV2R4cV9kWnpfU21naDBzX21hQmFCWkJGNWdTLW5tS1pBcnlDZ2c1Q1JxWHFyaDA0c2pHLWVkQU55ZGZiOWtNUXUxRXdSYzFvQW83aV9mWGtuZmdFRmdETmZvQUk0MnhSQ2dxa2hiWWlnNXBSV2xvQ3ExeDVsRWRHWld2eWgydzZLb0o5OVM3aVhrYVFsRkp5QV9yNWFMTWRxVVRCQlF6OWFyY0pFcDlza0h4Q01WdGZJS1U4QWN2X2lvNnY5bTJCYXBYQVlOVDlCcEtZbXhxYm5SQWQ1NmZRUk1YU3dmTWJJSHQzVHVOc21yM0x2OVFhcWo2djdYMHVpUjBHazFHcDNaRFhINThZX1ZDNWdvRThENzF2aXZNUXRISVVMa3JvTkZUbnNHNEZhRmVwVE1vZ09OOGphd0I5eGNYbHhBSW9qUVpxSURuTFdOUWQ1Qk5Nc0J4X3hFcWRBRmtFYVI0SlhDS3QzZmRCYXNZc20xSk0zRkFFelotX0ZiMjYtdkRtM2JBU0lxVU51Y01DaEVOVTZvNzUtRldreGJFZkU2YXktSVMtZ0pERnZhSU5mRnE3dTI2cnhWVGpHM3MzMjlvYmg3NlVKcnhyNUZUQ1BPbUFvRzFUdUF4Z090cEJ5YzBVLWl6TG5xZG05MlBnS21UTDhxYVpBNVBRSFB2RHM3bTVEcEtxZ1FEek9jbDZvblBTZElUdFprczh4OTdEWGNoNVl0YXk2TWtYb2JDbW15QVR4TVpXSDktZ2FxMkcyLWo4Z2tyRElDbDBoWndwLUpIVFVKN0JyNmJhb1Rqalh6aTVfOG9WX010SGJPemFyZGlKSEVPMTNKZkQ2N1NxRUN0VTZGMDNwUkpydjBPaXhISTJUeVc1T29IRUZhUjY4dnpoeFlQSWdlU1gxdVRMTXdjRFJWOFA5eGxZNHFES1l0X2lMQ25WY1VobWh0NWdGU2JabWJsVk0tNk1vbnVqOTlpaS1TZEgtbHVnTTRJMlZDMnZhX1BRbVlUZHZsUGZUckd6MENUMDZ0RngzbHFNRm5obUs1by1nYmVJQ1UtWks2aG1WSl9CNkx1U3BOQkVyU1RNNVVfdmlkNXo2Q0hpWl8wNExkZm9HMjdjSkc1M0oxVVVMWXhyQVBoLW91bkRmQlVGeUNETGViMVJ2VUNlamhJdlpFRHZzNk9iZlV4SVdCeGFYYW5XRnpyWThKVGFXQlp5UHJvNk5ySHRwMzJuR0o3ZHpXNXJTcDdNemRuZGs3Um1QUmRnbDdoUWVtdW9PSWEyT2VWT3BzWlNiMzVnM0NDaV9XeGZXQ2tJenNFRmlTTmtVSk9sck1OZS1uUTZGcEdMa0ZRSWxyNENrY0lIb0ZZeklKa3pac2ZYQ2pJcC1ha3JYLW5laVVodEZ1eW5kNmxKLW5IV2d5S3ZyWThwWXJtaGFpS2pkVHMtb2o1Y3J0VzVacld2VXBtamdPMHF5N0NmTW1MTGE3UDhqRWl2bFVVSzVJam9kRDZIa0tfY2YzQUtYYXRXQVcyT1o5Y3NTMXRiYkdBQmN6YVByektLOUVyZ19ST1hwOXFERmVMOWNxSC1LSHVFa3RkdkFwRjFKSER0V2tDUUJTNGtvWl9hR3owZmNKXzVBdXJ1b1AtcEhCUU11WGY2NWR6bUs0TW1Ec1dMcmJ1aGR3c21wWWFpT1BSdW5IM0g3dnhMX3g0bEVBTVNYNXpCaUN4bVpqWXowQTAwZG9ILXRNay1kX19oY2F4UHVYemNXOTV4WEpvZHVBV3RZVkFtWi1xS1NIX2xQMjk1amIxN0pTcjY3YWtsaDVnWUtsVC1hS2FfYnpqTmZ2bGxJQnJOZnU1ZDZWcHRVTmJlQ0VCTXVrNkhDcGN6cnl0WG45U2Z2S1hJRkxGWVVOVUtvNXBDYXgwS3VCbVI5VWZkLTZxZ0Ryc2RiTktWSGJoeWx0X1JxSGhIWHA2ZzcyVmM1clhTNFB5NUYtMWdiTzh3bWZYSUFQUzUxcE9uUWpfMHZMZjVhOUxMZzhWdmJmNm5hVldBeUNUdFlaWE9xUWRzRGh5QlE2NjZfckxiZVc3VHZHRktVbmNiNFVnRm1aVmozclFhdXRseDBpU3pkeXV0Q0NqZS1WVGIwZ04tNTVaYlFNb09UWHRxVlpNWVNveWtsR0J0TG1LNDNmU0FtSnk3UE4tYWV3Ykp3X2ZyT0dFdzRibTN6U0VLUVhfOXRPV0FNcnUwRXNLZjVOZ0x5bXZXWmFuSlZXdEhleTB6dzY1aUUycjlXUzhWYnpOQVBzbGlqMTljMFJNZ2t1S1JYSUV6MWRtUVpYbWRoLUItX0xXNUVsZ3hGc0J0X1ZhdW9YOXhQdURseEVXdC00TVMwNlBfSkhEMUR4UW0zbWlFME1xcTFYcnNETy1KNHcwR3dmazJNRlR0dGVMU0x2eUlXb1NjUzk3QnUzOUFZMU9yZExzeHZOYzRZOS1VRmRsazZINU5Fckt0MUpjVGtJd1hVMm0yX1dnV0NBWlM2UmtDdGxvOTBUWXM5dGV2UVNfZUlMSkkwNkV5YkxrcHdrVnFTNC1uNHlhM1lqcXZUdVV1cVNOUG1ia05BOUFCbTVSWWFqWndqVlJmRzNIejlDdXNLTk5EUmZIZTBCYm4tOFhDc0pBSmVqMklYSXhFXzN5b2NxenRFdHNZbDBiSEIyekdBT2NNa0Y4aW5SRC1LOVItTHJYclRmLWE0S0Y2ZDh0ZU9PUkw2OVl4UTBhdkdieTY0WnREX0pzTjJzYUM0a2kxV3pxbTJoaGtHMFVaLUFXTmotTXNXWUhFSGkxc0NBWTgzaDQ0RFJJM0NmcEZoQmVBUjFKYUNtZmU4Mm5uNGViWGVVbl8tNm1xTmlSb0ZkYTNvQjFERDlkOHVSOGRVYVJ6WnZVd1haYnNaMkx0YjZXbXZmOEoxVTdQ"
    master_key_two = b"Z0FBQUFBQmxkMmxRV296RnZOc3BrcG54eHlPZnRNd2JYbFhsQmJSSzlzdFEwQVZvSmdFMEd3aGlJN1lUSWFUcGFtblI4amtGdFM5UmhtS0psZ1pnRndYUktITUtiRnVCdjNySV9jTUpJRGZ2aWJIUXBrVDJsdVV4LTc4UWk5RXBrLTRhOC10bVh4RDNNdm9lbkx5WGJhXy1ia1RDZks5QVVEY0RWUW1aV3V2aFlmWkRrODlfX3Fkb09RVGZEeHoyQjdrUWI2ZEttcTNpa0dwU0RBRTdOVWxtdDVqcGlwY2JNTjlyNURRQ0RVOG1oR2stWXV5V2FxenlQdEhMMEtTS2h0VGJwNE5FTThXMUVEUFlWWmxncnlxLVFtM0I0b085UjRhYTNqYTZYOW9WQXZkUU5nUGl3bF8yY0ZEM0dsTUNtUGhEbENYRTROeTBwU1Q0MTU1Njc5TWdwMlprUFVINXZzNWNtRkNaR01WalZPR21LNzJoRFc3UmwyNHl1bTB6WW84NjFic216MkgzSzFnYUh1RjFyZ0N5aVVwd1VYM1BnYWx1UWl1ZXZJSFZzUGh6N0hSWUpiX25Dbmk0bEE0eW5zb1J4WnFtWHRVOU1sNTNjX2c2NU14MXdzNlZWYmZVdGVXeWNOVWNraWpJbHlRUjNCVElsRzl3VEpjaXh2VkhoUzVSUW91Qk5BdUdlMDU4ZTlWaWdyLVp1UnlSdm1QcVN2YXRfS1JTUXZ4dGVCMU9ZcGRodEtwY3BrcGlsZWxlUzFBVmR0NERIWVNkUkJHQlFzdERBSTlTM3JBbGlkYVBwUjVxd3FjWjZ6V3RhZDVWWGQzWFgyOXFMRGVfZTNIM1haOGd6V3J3QUhabHF5MVNxV1hMUVhVV1k0dVoyU3R4SnIzSzRVbDV3R19FbFBHdzcwRllYSGhNV1dDeUluUkRiSG54ZHE1NGZfd2tIdlJROTczMlBHZTMwQnVMUmZ1SExqLWdpdW9qMkFDNzU1dGh6V0dXWHlIZURDSGkzdUItejkybEJyUEJoU05zUmpJSy1la043bF8tck9NUXRKc1g2blk1cXpmQVp6YzRDeWsySnpSVGNEd191bnVLNDl0OW41RjdKV2tvMkhhU2VBQVlod2xuSFRFWm4xXzNmZ3IxaEx2LTE4Z2pTa3pWa1dyaUxmekxxc0xTZ1d3WVV3Q1hwUDlyS25YU0xXRUMxSWZzblFtMXRQZjlVR3REd1lxdnEtTTRpdWl0OTIyTFZNaVpobEFLWGZRVUhFUGhmRFUyZzBxZ0xzSmJfckxFNm0zeU56RTF3VVU4ejl6RHdkTTR6MWduMnVmeU44M2VRcWUtUVJYWEM1R29SdThhbVBPVzgzX0p2UzBLN19VTWUxZWw3TVY0WWJFZlY1bU1wTl9fS3k2TEY4Y1pVaXZua3hteEkyV1NvT3RpWHJvSzJXcldyemc3QjVCVVJVRF94Y3c3UEpmaTdkQzhldzdLQk9oSXV5Qzh3RVREWWExLXpkUkVXRFpKTnFiM1B2UGNrYTVLdVNTQ1ZMdXJMVGhMLUtnZ1l0bmMta19WMU9vWnpwWlAyLVdDUGhvSU9tb1V5b3Rtd3pIbGc5MVJwX1pra0ZKSkF4bExLb1lMRGM3ejhvQ3ZEY1VWdGtfMFQ4bkktdjFHMFMzeVVxVkJUQkRIWjdEZXhHLXQ1T3BkOWtvM0xNLWNMRGd4R1JERkNJQVZENkU4RE94ZG51UjVsRFhBQVVEeWJ4NENCUy1meGx3d0xqUXdLejBvN19tQTYwSXZuX3VQeUJNZGVxbFI3bDJwZXZiVlN1bDRXdFV2bGF0Z1NJVkZnQ2xFUTE3V040T01vNjk4T2phNzBYXzBXcGt3Q0NEeG9ZcjdwQVNRcnpSa3RwZEpqdGcxaE1KVnVkbFpWQXk1VW1Ra1N1WldTUUZfNTFZZ25BZ0NLampuZWtoYlFiOVA2QTRqZW94UFZwWmhXdWF6cnZ2RTlLTFZpbDNmbHV5ZmFETllIbkVTcDFsbjhSNVM2NXV0dWtyOGRsWFdWR0ZWTmM4SFhYbTl2UDJfbmwtZXRqcFBGSFp5WEhqOS1QY2lqUV9fdm5OQzRSSTBlYVJTZHlIWmdfcXVpbGp0SmJ2c21ORGVfRmZoVEphU1ZyM3l4SF9oRlRXcDBYc3p2eHpCQkdaNjVSWFREbDNtTWRPMll3Y0tpc3A3T215UEprdktENnFoSWU3aGZraW5aczAtLVZRMHEyVk9RR25jRTQ3anFVMGNTdFhqOWJqak5leFptR1J6QjN6T1kyVUdTdGliaUhMcUdMbDRtdDRVXzNCSU5ua0RweE9uc0M4clFQNjZQSEFuNHF3QTdFNlZ1SkRyQnZSd24xMUp4OFp1bGpQMEFkQmp4a3MyT00tRVJ4V2s0Z3hJWC1fM2ljUTM1TkVkdW5aOE5oSkEyOTZLNVVuR25pWUZwbDAyZ3FUYUFXV3FvRUwtcmh1X2xlWFd4S2kwd1g1TVFiV0pqVEZpLS14cnNSb0FId05IX3plQWlKQTFHSVlUUWg0QjFlbEpvTGdpMUNsQzlabGt0VDF1UE9hSkdfU2JoSWcwT1VfWmJ2TTI2Q255cVdrSEpqdjdQMkR0NERRRlVJMXdTUTgzeDN2SVBEVm9Ka19rVTR6ODM1M2cxdXdDZkdDdWE1OENWVk1ha0R2cmZ4TUxnTHVxVnY1Z2tNLWV3VGVCVE83VzVodEUtNWUtNTVPLU9OXzdISFNOVFk3SW5BVmhKck1qOXlPU0hOdk41MlIzZmotd1RUSDZneHFVdmdDdGl5VFhFM3VJV2UxR3haVERWRzF3TTZkYXA5d1U4akJSZzFkS2JpX0NTWmdYMTd4NWtxVnpmbTdvSk1ZX255cEZnTzg1dXZqRGRfWmpSdU4zYjdtdVMwWmxiYWREVk1kOFpHd3I5a2hkZWNKcmJhYjJyUkVvekpMTFFQUVhnd1ByeE9mV0UzdHpVMEdWV0dsT2VLbVR5dHlORDlrczhKcWJlVWNSV3VscDZweGRhN3lUelU3QlZ4REFycFFtbnliZTBoQ0NGdVItcUZyU21CY21NekEtSmVMUWZsUGhLajQ2c0R3UDRhQ1VicG55RXRRQk5tY25tY2M2ZGdGYzZRQWtqWUNJTVUwV3B0Z0RQZUFoMl9ZUVE2N2MyZU5objc1eUlQY2x6dHNhdHhBczR2TGNSa0kySHpEMjNINS1tUXZNdk5GUEI0WUpOeTIwRXd5aV9kVGF3OXZ4UUhwUk5Bc0o0T1BsXzNHSlFZVkNCVXRJZU9LS000VkNRS1BCZFVsYkFsTVYwaEVtZlQ1cWZfRkpJOEtHUTZUODNjUFo1aDAzU0lFUlVhbmMwV1Y3d1NnSGF0M1VLckxCTGYtU3lNVG93a0JtTWE2N2FCc1VxRWd2Q21pd2d4clhnNXAyazJKY1NLekhvVVBHU0xHY0lxMXlSUXFtNm9lLWxmdVZuZFFwV05tMEU4MEJFOHJmUGZpM2lXZFhKdjltbTROZUp2WFF1S1hSd184VFRhbVFmUVJtM09xcTFaNmJicDczQkdKNHN4T0RyNHRTb3N2ZnJzRWRsZmpRZlprTjVIdm81TFVVX0Q5Sm9nT0J6MkY4bk9wcTNCUmlXVUZjNVA3eVg0X0thb1JZX051UFhIV05MbGsyeXo1T1BydW8yekRWNkowTkZwUHd5dWswWkZORDNiLXJsWlVDdU5OT3NqYWo5Wlo5UFdPNnU1dGhUTm5IamFJQkRUZ1pPcnNoV21KWEtfWmNVRHVuaUVxdmxRckRJNF9iZV95dWRKTXhSUXNfTWo4VVJMVEhTYkhWM2tjRDhrX2hsdlh3"
    extralayerforpass = b'$2b$11$ssr3qHnRez3iKkd8TnbOpu'
    email = "testmail@gmail.com"
    rapi_key = b'$2b$10$HwD7QxtQZkEA4iGwofnGuOei4s3jm3XGV7VkOwDblAqexaHCVEQNO'

    # First data
    firstdata = master_key + typed_password + rapi_key + typed_password + email.encode("utf-8") + extralayerforpass + master_key_two + username.encode("utf-8")
    print("First Data:", firstdata)

    # Second data
    seconddata = extralayerforpass + email.encode("utf-8") + username.encode("utf-8") + typed_password
    print("Second Data:", seconddata)

    # Hashed password
    hashedpass = bcrypt.hashpw(firstdata, seconddata)
    print("Hashed Password:", hashedpass)

    if hashedpass == real_password:
        print("Success!")
        return {"success": True, "message": "Giriş başarılı!"}
    else:
        print("Error!")
        return {"success": False, "message": "Giriş hatası!"}



if __name__ == "__main__":
    apilogin()

```

**Comment by Eta06** [comment] 2023-12-11 20:18
And as additional information, I updated the bcrypt version to 4.1.1. (The error persists)

**Comment by charmander** [comment] 2023-12-12 01:19
The second argument to `hashpw` is a salt in a specific format, not any arbitrary data you want joined together; anything after the salt is silently ignored. The first argument also has a 72-character limit; anything after that is also silently ignored. This looks like a pretty serious misuse of bcrypt to begin with.

That said, maybe `hashpw` should validate that it’s being passed either a salt or an entire hash, and check the length of its input?

**Closed** 2023-12-14 17:14 UTC
