### ISSUE TITLE
AttributeError: module 'bcrypt' has no attribute '__about__' with new 4.1.3 version

### ISSUE THREAD

**Issue by Ayikoandrew** [pyca/bcrypt#792] opened 2024-05-06 15:54 UTC
![bug](https://github.com/pyca/bcrypt/assets/107671117/0346385a-5394-4ed6-b7c0-2b6fcc401ad5)
For bcrypt 4.1.3, I get this error/warning when I run the method verify. I have passlib 1.7.4 

```python
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def hash(password: str):
    return pwd_context.hash(password)

def verify(plain_password: str, hashed_password):
    return pwd_context.verify(plain_password, hashed_password)
```

Output

```shell
Traceback (most recent call last):
  File "/home/ayiko/Desktop/api_class/venv/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

**Comment by alex** [comment] 2024-05-06 15:55
Duplicate of #684 -- this is a warning and there's nothing we can do about it unfortunately.

**Comment by Ayikoandrew** [comment] 2024-05-06 15:59
Thanks for the response. I understand that this issue has been noted before. Is there any workaround or best practice to handle this warning in the meantime

**Comment by alex** [comment] 2024-05-06 16:00
The only suggestion I have is configuring the logging module to
silence this warning.
On Mon, May 6, 2024 at 11:59 AM Ayiko Andrew ***@***.***> wrote:
>
> Thanks for the response. I understand that this issue has been noted before. Is there any workaround or best practice to handle this warning in the meantime
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by Ayikoandrew** [comment] 2024-05-06 16:20
Thank you so much.

**Closed** 2024-05-07 03:25 UTC
