### ISSUE TITLE
No kdf() function

### ISSUE THREAD

**Issue by vincentbernat** [pyca/bcrypt#65] opened 2016-05-21 14:45 UTC
Hey!

py-bcrypt was providing a kdf() function but this is not the case for this module. Therefore, the compatibility with py-bcrypt is only partial. Would it be possible to provide a KDF function as well?

**Comment by reaperhulk** [comment] 2016-05-23 19:06
This is a dupe of #56 so I'm going to close this one.

**Comment by reaperhulk** [comment] 2016-05-23 19:06
(I am looking into adding this)

**Closed by reaperhulk** 2016-05-23 19:06 UTC
